[build]
  # This is where Netlify will look for your site output
  publish = "."
  
  # No build command needed as this is a static site
  command = ""

# Set up pretty URLs (removes .html extensions)
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Handle 404 errors with our custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Set custom headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 